-- 코드를 입력하세요
SELECT M.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE M JOIN  REST_REVIEW R ON M.MEMBER_ID =R.MEMBER_ID
WHERE R.MEMBER_ID in 
(SELECT MEMBER_ID 
FROM 
(SELECT MEMBER_ID, COUNT(MEMBER_ID) C 
FROM REST_REVIEW 
GROUP BY MEMBER_ID 
ORDER BY C DESC LIMIT 1) 
REST_REVIEW)
ORDER BY REVIEW_DATE,REVIEW_TEXT