-- 코드를 입력하세요
#  SUM(SALES) * PRICE
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SUM(SALES * PRICE)) AS TOTAL_SALES
FROM (
    SELECT *
    FROM BOOK
    INNER JOIN AUTHOR USING (AUTHOR_ID)
    INNER JOIN BOOK_SALES USING (BOOK_ID)
    WHERE MONTH(SALES_DATE) = '01'
) AS SUB
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;